apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cn7avqdm8-nodejs
  janus-idp.io/tekton: cn7avqdm8-nodejs
  backstage.io/kubernetes-id: cn7avqdm8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cn7avqdm8-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
